version: '3.8'

services:
  SIS:
    build: SIS                 # carpeta donde está tu Dockerfile y el JAR
    container_name: sis_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_URL: jdbc:postgresql://sis-db:5432/sis
      DB_USER_NAME: postgres
      DB_PASSWORD: tu_password
    depends_on:
      sis-db:
        condition: service_healthy

  sis-db:
    image: postgres:16
    container_name: sis_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sis"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
