#application-postgres.properties
# --- JDBC (usa env vars si existen; si no, toma los valores "quemados") ---
spring.datasource.url=${DB_URL:jdbc:postgresql://sis-db:5432/sis}
#para correr en pruebas con posgres usar localhost en vez de sis-db
#levantar solo base de datos docker: docker compose up -d sis-db

# URL para acceder a la base de datos
spring.datasource.username=${DB_USER_NAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- App ---
spring.application.name=sis-app

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
# Puedes usar una de las dos; dejo ambas por si quieres el estilo del tutorial:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# (alternativa equivalente)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Server ---
server.port=8080
