# application.properties
spring.application.name=sis-app 
#Debe coincidir SI O SI CON EL EMPAQUETADO DE LA MAQUINA DOCKER!!!

# Cuando construimos y no se encuentra sis-app se va a application-test.properties
# Hace lo que esta en test properties


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always --> Es importante enteder que este init va a buscar cualquier shcema/data.sql para SIEMPRE
# INICIALIZAR LA BASE DE DATOS, es por esto que lo tenemos que poner en never para que solo inicie con datos de ejemplo en
# test. Para postgres probablemente genere problemas con la llave primaria.
spring.sql.init.mode=never


# CD pipeline metrics
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# BOT DE SMS
telegram.bot.token=8261960298:AAFLS63reoC56dZ1nkNhQ7SFgUXQUnhhoBQ
telegram.chat.id=1388034338
# Juandacun: 1388034338
# Sexmuel: 1917602230
# Cargar datos de prueba

# PERFIL ACTIVO (IMPORTANTE) SUPER IMPORTANT TO CHANGE WHEN MAKING THE IMAGE!!!!
spring.profiles.active=postgres
