spring.application.name=sis-app 
#Debe coincidir SI O SI CON EL EMPAQUETADO DE LA MAQUINA DOCKER!!!

# Cuando construimos y no se encuentra sis-app se va a application-test.properties
# Hace lo que esta en test properties

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# BOT DE SMS
telegram.bot.token=8261960298:AAFLS63reoC56dZ1nkNhQ7SFgUXQUnhhoBQ
telegram.chat.id=1388034338
# Juandacun: 1388034338
# Sexmuel: 1917602230
# Cargar datos de prueba
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
