package com.sis.Model.Enum;

public enum TipoEvento {
    // Admisión
    PACIENTE_LLEGADA,
    TICKET_CREADO,
    TICKET_CANCELADO,
    ESTADO_TICKET_ACTUALIZADO,

    // Triage
    NUEVO_TRIAGE,
    TRIAGE_COMPLETADO,
    PRIORIDAD_ACTUALIZADA,

    // Consulta
    CONSULTA_INICIADA,
    CITA_CONFIRMADA,
    CONSULTA_FINALIZADA,

    // Diagnóstico
    DIAGNOSTICO_LISTO,
    DIAGNOSTICO_REGISTRADO,
    DIAGNOSTICO_ACTUALIZADO,

    // Tratamiento
    TRATAMIENTO_AGREGADO,
    MEDICAMENTO_PRESCRITO,

    // Resultados
    RESULTADO_DISPONIBLE
}