spring.application.name=sis-app 
#Debe coincidir SI O SI CON EL EMPAQUETADO DE LA M�QUINA DOCKER!!!

# Cuando construimos y no se encuentra sis-app se va a application-test.properties
# Hace lo que est� en test properties

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
